service: vault-test
provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role: arn:aws:iam::027755483893:role/service-role/proposals-service-audit-table-backup-role-ilv91rl1
  environment:
    VAULT_ADDR: "https://vault.secfi.com"
    VAULT_AUTH_ROLE: "proposals-audit-backup"
    VAULT_AUTH_PROVIDER: "aws"
    VAULT_SECRET_PATH: "kv/secret/production/backend/lambda"
    VAULT_SECRET_FILE: "/tmp/secret.json"
    
functions:
  hello:
    handler: handler.testVault
    layers:
      - "arn:aws:lambda:us-west-2:634166935893:layer:vault-lambda-extension:14"
