language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
    - ${SERVICE_PATH}/node_modules
install:
    - yarn global add serverless
    - travis_retry yarn install
    - cd ${SERVICE_PATH}
    - travis_retry yarn install
    - cd -

.feature_env: &feature_env
  - CLUSTER=development
  - ENVIRONMENT=development
  - TAG=${TRAVIS_COMMIT}
  - AWS_REGION=eu-west-1
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEVELOPMENT}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}
  - AWS_DEFAULT_REGION=${AWS_REGION}

.staging_env: &staging_env
  - CLUSTER=staging
  - ENVIRONMENT=staging
  - TAG=${TRAVIS_COMMIT}
  - AWS_REGION=eu-west-1
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_STAGING}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_STAGING}
  - AWS_DEFAULT_REGION=${AWS_REGION}

.production_env: &production_env
  - CLUSTER=production
  - ENVIRONMENT=production
  - TAG=${TRAVIS_COMMIT}
  - AWS_REGION=us-west-2
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PRODUCTION}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PRODUCTION}
  - AWS_DEFAULT_REGION=${AWS_REGION}

.deploy_script: &deploy_script |-
    serverless deploy -s ${ENVIRONMENT} -r ${AWS_REGION}
    cd -

.deploy: &deploy
  script:
    - cd init-user
    - *deploy_script
    - cd create-post
    - *deploy_script

jobs:
  include:
    - stage: test
      name: Run tests
      if: type = pull_request
      env: *feature_env
      script:
        - yarn run jest
    
    - stage: deploy
      name: Deploy to feature env
      if: type = pull_request AND (head_branch =~ ^bug/ OR head_branch =~ ^chore/ OR head_branch =~ ^feature/) AND branch = master
      env: *feature_env
      <<: *deploy